---
title: "Assignment_9"
author: "Hemal Agarwal"
date: "December 5, 2016"
output: pdf_document
---
#1 Data
```{r}

#setwd("C:/Users/Adroit/Desktop/CourseProject")
Project.Data <- read.csv("PCA_ExampleData.csv",header=TRUE,sep=",")
Project.Data[1:10,]

Data.Levels<-as.numeric(Project.Data[1,])
Project.Data<-Project.Data[-1,]
head(Project.Data)

matplot(Project.Data,type="l")

```
# 2 PCA

```{r}
Project.Data.PCA <- princomp(Project.Data)
names(Project.Data.PCA)

Project.Data.PCA$loadings

matplot(Data.Levels,Project.Data.PCA$loadings[,1:3],type = "l",ylab = "Loadings")
matplot(Project.Data.PCA$scores[,1:3],type="l",lty=c(1,2,3),lwd=2,col=c("black","red","green"))
plot(Project.Data.PCA)
(Project.Data.PCA$sdev)^2
````

***Estimate PCA using manual calculation with eigen(). For this recall the steps on slide 16 of the lecture notes.***

```{r}
setwd("C:/Users/Adroit/Desktop/CourseProject")
Project.Data <- read.csv("PCA_ExampleData.csv",header=TRUE,sep=",")
Project.Data<-Project.Data[-1,]
mean_vector <- as.vector(apply(as.matrix(Project.Data),2, mean))
mean_matrix <- matrix(mean_vector, length(Project.Data$V1),length(mean_vector), byrow= TRUE)
centered_matrix <- as.matrix(Project.Data) - as.matrix(mean_matrix)
head(centered_matrix)

covariance_matrix <-cov(centered_matrix)
eigen_values<-eigen(covariance_matrix)
eigen_values$vectors
Project.Data.PCA$loadings
```
***Calculate 3 factor loadings using PCA and using manual method based on eigen-decomposition. Combine them in one matrix Project.Data.PCA.by.eigen.Loadings and compare***

```{r}
matplot(eigen_values$vectors[,c(1,2,3)],type = "l")
Project.Data.PCA.Eigen.Loadings= cbind(L1.eigen = eigen_values$vectors[,1],L2.eigen = eigen_values$vectors[,2],L3.eigen= eigen_values$vectors[,3], L1.PCA=Project.Data.PCA$loadings[,1],L2.PCA = Project.Data.PCA$loadings[,2],L3.PCA = Project.Data.PCA$loadings[,3]   )
Project.Data.PCA.Eigen.Loadings
```

